### ISSUE TITLE
Clarify that Trace Viewer not functional when server offline

### ISSUE THREAD

**Issue by ebugden** [eclipse-cdt-cloud/theia-trace-extension#321]
When the server is offline, this information need to be communicated in a permanent and obvious way:

| Critical information | Solution ideas |
|----|----|
| **The tool cannot be used ...**             |   Make the tool look and feel broken/unresponsive: Prevent interactions (ex. opening analyses), Fade out the associated UI (ex. Trace viewer side panel, trace tabs)                     |
| **... because the trace server is offline**              |   Write a more precise permanent message like "Trace Viewer Critical Error: Trace server offline"                     |
| Bonus: Point the user towards how they can fix the problem | Should they restart the server? Change the configuration? |

Related: [#53 comment](https://github.com/theia-ide/theia-trace-extension/issues/53#issuecomment-782396960), #234

----

~~Right now, when the trace server is offline the only hint to users is the bottom bar saying "Offline".~~ PR #298 removed the server start/stop buttons from the bottom bar.

![image](https://user-images.githubusercontent.com/28311615/112387347-075fd180-8cc8-11eb-9b7d-d46bf189e5f4.png)

This is not clear enough considering that the **Trace Viewer is unusable if the trace server is offline**. 

| When the server is offline, it needs to be obvious to users that: | Neither of these things are clear in the current implementation: |
|----|----|
| **The tool cannot be used** - This is a critical failure              |   Right now, users can continue to attempt to add views (or interact with current views) which will never successfully update                     |
| **Why the tool cannot be used** - The trace server is offline              |   It's virtually impossible to guess that "Offline" means "The trace server is offline"                     |

----

CC: @ssmagula

**Comment by ebugden** [comment]
PR #298 removed the server start/stop buttons from the bottom bar.

**Comment by ebugden** [comment]
The need for this was highlighted again in the user survey completed in November 2021.

Clarify when the trace server is offline:
* This is critical information because the Trace Viewer does not work without the Trace Server
* Users seem to not notice the bottom bar. Even if they did notice, they wouldn’t be able to guess that “Offline” means “The trace server is offline”.

**Comment by hriday-panchasara** [comment]
@ebugden Wanted to get your opinion on an implementation we've been working on. The idea is to use polling to call the '/health' endpoint periodically (every 5 seconds for example), and make use of a status LED to indicate server status. The LED would indicate failure if the server is offline or when the '/health' endpoint returns 'status: "down"'. The LED has a tooltip to show more details when hovered:
![Screen Shot 2022-02-01 at 11 43 17 AM](https://user-images.githubusercontent.com/92893187/152021841-b08ca967-9d97-4b84-a0ea-75722244e457.png)
![Screen Shot 2022-02-01 at 11 43 57 AM](https://user-images.githubusercontent.com/92893187/152021869-a3679824-0cce-4bd6-a4a7-43266a83b36b.png)

We stop polling when the trace viewer side panel is detached, so that the ping is not constantly sent if the user decides to not continue with trace analysis

**Comment by ebugden** [comment]
@hriday-panchasara Thank you for looking into this! @ssmagula could you review this design as I'm not actively contributing to the project now?
