### ISSUE TITLE
Problem with project setup

### ISSUE THREAD

**Issue by andy2ndlife** [eclipse-cdt-cloud/theia-trace-extension#705]
I have successfully installed Visual Studio latest version installed with c,c++ IDE and compiler, and Python.  

I also noticed that the README instruction didn't include the below.  I had to find out myself.

Before install with yarn, I need check node version which needs to be greater than 12.14.0, and 
Python 3.7 need to be installed as well.

I am at the step where I need to install all the dependencies from the YARN INSTALL command.  However, I have encountered an error which I couldn't figure out how to resolve it.

Here is the error message:
Error: spawn C:\Users\Andy Vuong\Documents\theia-trace-extension\examples\browser\node_modules\@theia\application-manager\node_modules\.bin\webpack.cmd ENOENT

I would like to ask for suggestions on how to resolve this error.  Please look at the attachment as well

![error](https://user-images.githubusercontent.com/1907841/158047244-f8f8dc8f-2e71-4cd1-b4d0-cee6c5a3219c.PNG)

**Comment by andy2ndlife** [comment]
Any guidance would be greatly appreciated.  Thanks!

**Comment by hoangphamEclipse** [comment]
Hi @andy2ndlife, could you provide the exact step that causes this error in the documentation? A link to the step would be appreciated.

**Comment by andy2ndlife** [comment]
Hi @hoangphamEclipse , After I install the required installation as required like node, python, visual studio, then in the root folder  I typed `yarn install` and then this error happened. Could you guide me in that case, I'm using Windows 10 System.

**Comment by hoangphamEclipse** [comment]
Sure! 

Based on the information you provided, I assumed that you have completed [the steps to set up Theia](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#building-on-windows). So the next step would be building the trace extension locally. You can find the steps [here](https://github.com/theia-ide/theia-trace-extension#build-the-extension-and-example-application).

As written in the second link, the command you need to run is only `yarn` and not `yarn install`. Just to confirm, are you working on Windows?

**Comment by andy2ndlife** [comment]
Theia is running on localhost:3000, but when I try to trace extension build locally it get error
![theia-1](https://user-images.githubusercontent.com/1907841/158463404-2c37231e-242f-4269-88cf-56223857a724.PNG)

**Comment by hoangphamEclipse** [comment]
Which command did you run that produce this error? Is this a different error? Please confirm.

**Comment by andy2ndlife** [comment]
I have only run `yarn` now instead of `yarn install`

**Comment by hoangphamEclipse** [comment]
The error is `'C:\Users\Andy' is not recognized as an internal or external command`. There is a space (at `Andy Vuong`) in the local path of the Trace Extension repo on your machine:
```
C:\Users\Andy Vuong\Documents\theia-ext>
```
This might be the cause of the issue since spaces and paths don't play along very well in command lines. Can you clone the extension somewhere else and try again? (or you can rename the folder Andy Vuong - which I don't think is a good idea since it is under the Users folder).

**Comment by andy2ndlife** [comment]
You are absolutely correct, Now it run without error, can you please guide me on the next steps

**Comment by hoangphamEclipse** [comment]
You will need to run the trace server next, follow the instructions [here](https://github.com/theia-ide/theia-trace-extension#run-the-trace-server) [1]. 

However, since you are on Windows, do not run `yarn: download` as by default all the instructions here are for Linux. Instead, download the trace server for Windows [here](https://download.eclipse.org/tracecompass.incubator/trace-server/rcp/?d) [2] (this link came from [1] - I'm just being explicit here). Download the Trace Server for Windows `trace-compass-server-latest-win32.win32.x86_64.tar.gz`. 

Then you have to extract it into `theia-trace-extension/trace-compass-server`. Make sure you have the `trace-compass-server.exe` in the extracted folder. Then you can proceed with running `yarn start:server` to start the server.

After starting the server, you can start the app in the browser, see [here](https://github.com/theia-ide/theia-trace-extension#run-the-example-app) [3]. If you encounter any issues in this step, see [this PR](https://github.com/theia-ide/theia-trace-extension/pull/708) [4] for more details

**Comment by hoangphamEclipse** [comment]
@bhufmann Do you think we need to improve the documentation for installing the Trace Server to be more explicit for Windows users?

**Comment by andy2ndlife** [comment]
Definitely.  I am taking notes and steps a long the way so that I can contribute in rewriting the installation documentation.

**Comment by andy2ndlife** [comment]
I think I get closer, I have follow those steps and when run `yarn start:server` its getting error. Error seems to JDK that I have installed like a versioning issue, I have installed jdk-17.0.2 (64) and also assign path variables.  Please see the error

![theia-2](https://user-images.githubusercontent.com/1907841/158588919-aeda1bd3-cba3-4f1f-9c40-dec266e96ae6.PNG)

**Comment by hoangphamEclipse** [comment]
If I remember correctly you need to get Java 11 for the Trace Server to run. I am not sure if version 17 will work.

**Comment by andy2ndlife** [comment]
I have tried but it still show the same error

**Comment by hoangphamEclipse** [comment]
Can you check if the right version is set using `java --version`?

**Comment by andy2ndlife** [comment]
Please check the image
![GitPost](https://user-images.githubusercontent.com/1907841/160677311-53c950de-a66a-4f68-9a18-ae0c7c4aae77.PNG)
Now, I am using Java 11 and the problem remain same. 
May be I am missing something. 
Please guide me

**Comment by bhufmann** [comment]
Sorry I missed this conversation and for the late reply. 

> Now, I am using Java 11 and the problem remain same. May be I am missing something. Please guide me

Looking at the screenshot it mentions exit code 3, which means that the trace server workspace is already in use. Either a trace server is already running, or the lock file of the workspace was not removed (happens in very rare cases for a crash).

Please make sure that the trace server is not running, or delete the `.lock` file in the workspace if no server is already running.

The trace server workspace in the users home directory under `.tracecompass-webapp`. The `.lock` file is in the sub-directory `.metadata`.

I hope this helps.
