### ISSUE TITLE
Issue: Overview should have inverted selection

### ISSUE THREAD

**Issue by MatthewKhouzam** [eclipse-cdt-cloud/theia-trace-extension#857]
Current behaviour: the selected area of a trace is "oranged" out, and the unselected area is in full colour. This seems to be counter-intuitive to read.

Suggested behaviour: the selected area of a trace is the only area not "oranged" out.

**Comment by hoangphamEclipse** [comment]
Picking up this issue.

**Comment by hoangphamEclipse** [comment]
I have a question for debate. As you can see in the picture below, with the color scheme inversion, the unselected area of the view range is greyed out (which is good). However, when we select a new view range with drag and drop, we use the color orange too to indicate the area that the user selected before applying the changes. I don't know should we keep it this way, or should I also do the same thing with the selected view range (grey out and invert).

![image](https://user-images.githubusercontent.com/92533264/199251132-01a3b9e6-c6c9-4f5d-854f-5e7bd075598d.png)

**Comment by Rodrigoplp-work** [comment]
Great question!

I see four shades now. What are they?

1: background (#edeff2);
2: selection (#f5f7fb);
3: zoomed area (#f3e8cc);
4: ? (#ede1c4)

![overview](https://user-images.githubusercontent.com/88502808/199252903-54093efd-1a3f-48e8-a4b6-3710673ea176.png)

**Comment by hoangphamEclipse** [comment]
So the colors are:

1: Background/Unselected range
2: Selected range
3: User new selected range (before it is applied), which is orange. The color 3 is the overlap of the orange color and 2.
4: User new selected range (before it is applied), which is orange. The color 4 is the overlap of the orange color and 1.
5: Zoom area, the previous screenshot did not include one.

![image](https://user-images.githubusercontent.com/92533264/199256006-2e051495-3cf4-48a1-bddd-3a8422d1fed3.png)

**Comment by hoangphamEclipse** [comment]
I added 2 videos demonstrating the 2 UI/UX implementations that I propose. In both case, the paler region is the zoom range, while the greyish area is the unselected range.

https://user-images.githubusercontent.com/92533264/199332726-28c1343e-6719-4a10-b7f0-71e7b3b638b0.mp4

For this implementation, when the user selects a new zoom range, an orange overlay is used to displayed the new zoom range. I prefer this implementation because it clearly differentiates the new zoom range (orange) and the old zoom range (no overlay) for the user.

https://user-images.githubusercontent.com/92533264/199333513-37c2340d-dd76-48cd-9600-1396aee7fae9.mp4

For the second implementation,  when the user selects a new zoom range, we also use the same color scheme as the current zoom range. This implementation provides consistency, but not very user friendly in my opinion.

What are your thoughts on this?

**Comment by hoangphamEclipse** [comment]
Sounds good Rodrigo!
