### ISSUE TITLE
Launching the trace viewer using docker

### ISSUE THREAD

**Issue by OljaH** [eclipse-cdt-cloud/theia-trace-extension#908]
Is there a way to launch the trace viewer in browser using docker? 
Similar to how the Gitpod demo works, but without the Gitpod.

**Comment by MatthewKhouzam** [comment]
Hi @OljaH , I believe @arfio and @frallax have made efforts into containerizing trace servers/trace viewers. I've seen demos and they look good, but I have never done it myself. Consider this a "Ping" reply. :)

**Comment by OljaH** [comment]
Hi @MatthewKhouzam, thank you for the reply, that sounds great! :) I hope that @arfio and @frallax would be able to provide me some more information.

**Comment by OljaH** [comment]
My use case is the application for a university project where I need to analyze and visualize traces. 

It is an angular app where I would like to upload a folder with ctf files and visualize them. So my idea is to package those files into a docker container with theia and its trace extension (if possible), so I can run theia trace extension in the browser (similarly in Gitpod example) with my traces.

I am also open to other suggestions on how this could be done.

**Comment by arfio** [comment]
Hi @OljaH , I already experimented with having both the trace-server and theia-trace-extension on a docker, and it is always required to have both on the same machine so that they share the file system, because the theia-trace-extension only sends the path of the traces to the server.

In your case, the angular app only needs to copy the trace files in the docker container. You might have to write some code to detect and aggregate/separate the traces depending on what you want, as the theia-trace-extension will put all the traces into one experiment by default. 

Another way of doing things would be to support copying files from your computer to the Theia UI and then opening the traces there. Something along those lines: https://github.com/microsoft/vscode-docs/blob/master/remote-release-notes/v1_36.md#drag-and-drop-to-and-from-the-explorer

**Comment by OljaH** [comment]
Hi @arfio, I understand. Thank you for the answer and the explanation!

**Comment by frallax** [comment]
Hi all,

just to add a few lines about my experience with theia-trace-ext, trace-server and docker.
I agree with @arfio, currently the "best" way to use the tools is to put trace-server (backend) and theia-trace-ext (frontend) on the same docker image.
This is mainly because of the "open trace" feature of the theia-trace-ext, which looks only to the file system where the front-end is running.
Hence, if you do not have a shared file system between backend and frontend, it is difficult to use that feature.

I have had use cases where running trace-server (backend) and theia-trace-ext (frontend) in separate containers was useful too.
In that case, the server was "loaded" with traces from a network disk using some scripts, and the theia-trace-ext (frontend) was used purely as "consumer" to visualize traces (i.e. not loading them on the server).

However, to answer @OljaH question, yes, running the trace viewer application on a docker container it is possible, and can be done with multiple flavors depending on your needs.
The main flavors I tested are:
- trace-server + theia-trace-ext in the same container
- trace-server in its own container, theia-trace-ext in its own container

If you are searching an example of "how to do it", I think that there are some Dockerfiles spread here and there, such as [this][1] or [this][2] (these are only for the trace-server).

@MatthewKhouzam, @arfio do you know if there is any "official" Docker image for the "flavors" I listed above?
If not, should we start an initiative to have some "common/reference" Dockerfiles for the different scenarios?
I think that it would be beneficial not only for @OljaH, but also for other people, to collaborate to keep the image sizes as small as possible, and to maybe publish them to DockerHub in the future.
I'd be happy to drive this initiative if nobody else is already on this.

[1]: https://git.eclipse.org/r/c/tracecompass.incubator/org.eclipse.tracecompass.incubator/+/192567
[2]: https://git.eclipse.org/r/c/tracecompass.incubator/org.eclipse.tracecompass.incubator/+/122361

**Comment by arfio** [comment]
I have some docker images for TraceCompass that I want to upload to dockerhub and maintain up to date. I have not setup the build yet. However I do not have any plans for a trace-server + theia-trace-extension in the same container.
As far as I know there are not any official Docker images that already exist on docker hub.

**Comment by frallax** [comment]
> I have some docker images for TraceCompass that I want to upload to dockerhub and maintain up to date. I have not setup the build yet. However I do not have any plans for a trace-server + theia-trace-extension in the same container. As far as I know there are not any official Docker images that already exist on docker hub.

Sounds great! Could you then start by sharing the existing Dockerfiles then, so that we have "reference" ones and we do not come with our custom solutions (apart when needed)? I am guessing that the trace-server Dockerfile should be a "pull request" in the incubator repo, while the theia-trace-ext should be a pull request for this repo?

Or do you have other plans on how to deliver the Dockerfiles and the images on Docker hub?

**Comment by OljaH** [comment]
Hi @frallax , thanks for your reply and your experience shared here. All that helps me in building my solution :)
I agree with you that it would be useful, probably for other people too, to have some reference Dockerfiles, as a starting point for different use cases of theia-trace-extension. So it would be great if @arfio  could share them.

**Comment by arfio** [comment]
@frallax To be more precise, I have two Dockerfiles, one for Trace Compass and the other for Trace Compass server.
I do not have any for Theia-trace-extension. I will share them as soon as possible.

**Comment by OljaH** [comment]
Hello everyone,

Thanks again for the help with containerizing theia trace extension. 
I successfully used Docker image you shared for my use case.

However, after the latest update, it stopped working. I get the following error:
     Failed to start the frontend application.
     Error: Cannot apply @injectable decorator multiple times.

I've read that this usually happens when multiple @theia/core dependencies with different versions are installed under the node_modules. Therefore, I tried to set all packages that are @theia/core dependent to the same version in package.json but with no success.

After experimenting with different version I managed to run the image again with theia 1.17.2. 

So, I am wondering if you have any ideas about how to solve this issue and make the image work again, for 1.29 or 1.34 version?

**Comment by frallax** [comment]
@OljaH : I updated the example-package.json file and it builds successfully for me now. Please try and let us know if it solves the issue for you. The example-package.json is almost a copy of the examples/browser/package.json file, so when the latest gets updated, the former has to be updated too.

@MatthewKhouzam , @marco-miller : would it be possible to get the commit solving this issue being reviewed and hopefully merged (if considered good enough), so that #908 is resolved?

**Comment by OljaH** [comment]
@frallax It works now, thank you!

**Comment by marco-miller** [comment]
> @MatthewKhouzam , @marco-miller : would it be possible to get the commit solving this issue being reviewed and hopefully merged (if considered good enough), so that #908 is resolved?

I just added @hoangphamEclipse as 1st Reviewer for #926, as recently agreed with him.

**Comment by marco-miller** [comment]
> > @MatthewKhouzam , @marco-miller : would it be possible to get the commit solving this issue being reviewed and hopefully merged (if considered good enough), so that #908 is resolved?
> 
> I just added @hoangphamEclipse as 1st Reviewer for #926, as recently agreed with him.

I'm now first starting on this review; thanks everyone.
